services:
  postgres:
    image: postgres:16-alpine
    container_name: poroda-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: poroda
      POSTGRES_PASSWORD: poroda
      POSTGRES_DB: poroda
    ports:
      - "5432:5432"
    volumes:
      - poroda_pgdata:/var/lib/postgresql/data

volumes:
  poroda_pgdata:
